### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by sheevy** [PTsolvers/gpu-workshop-JuliaCon23#4]
I just wanted to thank the authors for this workshop and for going above and beyond to make it available to follow online for people who cannot attend in person
🥇

**Comment by luraess** [comment]
Welcome @sheevy for your feedback! I hope you'll be able to follow some online streaming, or watch the recording later. In any case, do not hesitate to reach out!

**Comment by sheevy** [comment]
@luraess I guess there's no stream/recording? Not to worry, the repo is so detailed it should be straighforward to do it without a video.
